name: clang-format Check

on:
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'

permissions:
  contents: read

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'config'
          - 'examples'
          - 'include'
          - 'src'
          - 'test/include'
          - 'test/src'
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@3a18028048f01a66653b4e3bf8d968d2e7e2cb8b # v4.17.0
      with:
        clang-format-version: '18'
        check-path: ${{ matrix.path }}
        include-regex: '^.*\.(hpp|cpp|h\.in|c)$'
        fallback-style: 'Google'
